### ISSUE TITLE
spawn zcashd ENOENT

### ISSUE THREAD

**Issue by AriseBank** [radix42/zcash-block-explorer#2]
[2017-07-14T05:15:16.597Z] error: Error: spawn zcashd ENOENT
   at exports._errnoException (util.js:907:11)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
   at onErrorNT (internal/child_process.js:363:16)
   at nextTickCallbackWith2Args (node.js:511:9)
   at process._tickCallback (node.js:425:17)

**Comment by AriseBank** [comment]
Solved through installing the binary manually. I missed your past issue. Thanks for an awesome bash script!

**Comment by radix42** [comment]
oh good, I'm glad you figured it out, my inbox is a trashfire right now and
I had just gotten to this right now!
